import argparse
import difflib
import sys
from pathlib import Path

from app.config import REPO_ROOT, Settings

TARGET = REPO_ROOT / ".env.example"

SECRET_SUFFIXES = ("_api_key", "_token", "_secret_key", "_password")

NOT_REALLY_SECRET: set[str] = set()

EXTRA_NOTES: dict[str, str] = {}

SECTIONS: list[tuple[str, tuple[str, ...]]] = [
    ("Core", ("environment", "database_url")),
    ("Object storage (MinIO)", ("minio_",)),
    ("Streaming relay", ("go2rtc_", "replay_")),
    ("AI providers", ("ai_provider", "gemini_", "openai_", "openrouter_", "live_ai_", "chat_")),
    ("Text to speech (Apple Silicon only)", ("tts_",)),
    ("Detection worker", ("worker_fps", "yolo_", "min_track_age_s", "motion_", "render_workers")),
    ("Semantic search", ("clip_",)),
    ("Alerts", ("telegram_",)),
    (
        "Authentication",
        (
            "auth_",
            "access_token_",
            "refresh_token_",
            "cookie_",
            "allow_",
        ),
    ),
    ("Filesystem", ("data_dir",)),
    ("HTTP / logging", ("cors_", "log_")),
    ("Misc", ("video_source",)),
]


def _is_secret(name: str) -> bool:
    if name in NOT_REALLY_SECRET:
        return False
    return any(name.endswith(s) for s in SECRET_SUFFIXES)


def _section_for(name: str) -> str:
    for title, prefixes in SECTIONS:
        if any(name == p or name.startswith(p) for p in prefixes):
            return title
    return "Other"


def render() -> str:
    lines = [
        "# Generated by `python -m scripts.gen_env_example --write` — do not edit by hand.",
        "# Every value here is the code default from backend/app/config.py.",
        "# Secrets are intentionally blank.",
    ]

    grouped: dict[str, list[str]] = {}
    for name, field in Settings.model_fields.items():
        env_key = name.upper()
        if _is_secret(name):
            value = ""
        else:
            default = field.default
            value = "" if default is None else str(default)
            if isinstance(default, bool):
                value = str(default).lower()
        entry = ""
        if field.description:
            entry += f"# {field.description}\n"
        if name in EXTRA_NOTES:
            entry += f"# {EXTRA_NOTES[name]}\n"
        entry += f"{env_key}={value}"
        grouped.setdefault(_section_for(name), []).append(entry)

    ordered = [t for t, _ in SECTIONS] + ["Other"]
    for title in ordered:
        entries = grouped.get(title)
        if not entries:
            continue
        lines.append("")
        lines.append(f"# --- {title} ---")
        lines.extend(entries)

    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--check", action="store_true", help="fail if .env.example is stale")
    group.add_argument("--write", action="store_true", help="regenerate .env.example")
    args = parser.parse_args()

    expected = render()

    if args.write:
        TARGET.write_text(expected)
        print(f"wrote {TARGET}")
        return 0

    actual = Path(TARGET).read_text() if TARGET.exists() else ""
    if actual == expected:
        print(f"{TARGET.name} is in sync with Settings")
        return 0

    print(f"{TARGET.name} is out of sync with app/config.py:\n")
    sys.stdout.writelines(
        difflib.unified_diff(
            actual.splitlines(keepends=True),
            expected.splitlines(keepends=True),
            fromfile="current",
            tofile="expected",
        )
    )
    print("\nRun: python -m scripts.gen_env_example --write")
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
